name: PrismOracle
main: me.botsko.prismoracle.PrismOracle
version: nightly
softdepend: [Prism]
default: op
commands:
   seen:
      description: Display join and last seen dates for a player.
      usage: /seen [player]